# ROOT LEVEL - Security context
securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

# ROOT LEVEL - Extra volumes
extraVolumes:
  - name: tempo-data
    emptyDir: {}

# ROOT LEVEL - Persistence
persistence:
  enabled: false

# TEMPO SECTION
tempo:
  repository: grafana/tempo
  tag: "2.3.1"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "300m"
  
  # Volume mounts under tempo
  extraVolumeMounts:
    - name: tempo-data
      mountPath: /var/tempo
  
  # Custom retention
  retention: 48h
  
  # Storage configuration
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  
  # Server configuration  
  server:
    http_listen_port: 3100
  
  # Receivers configuration
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
